In [1]:
print('NumPy Practice')

import numpy as np

In [3]:
a = np.array([2,3,4])

In [5]:
b = np.array([2,3,4,5,6,2]).reshape(3,2)
b

array([[2, 3],
       [4, 5],
       [6, 2]])

In [6]:
np.random.rand(4)

array([0.78884031, 0.03280259, 0.33295345, 0.89818099])

In [9]:
np.random.randint(0,500)


53

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])